# Site settings
title: "The Environmentalist"
email: Ramezani.M@ut.ac.ir
description: "The Environmentalist"
baseurl: ""
url: "http://mostafaramezani.com/"
title_description: "🦁I love to provide solutions to most sophisticated human race problems. Questions like water scarcity, overpassing droughts, saving endangered species, remediating aquifers, and providing clean and hight quality water for all earth population. I use computers to do so. I develop models and work with a team consisted of best hydrologist from all over the world. I may be a keen environmentalist, but above all, I am a programmer."

title_image: "https://en.gravatar.com/userimage/138194692/1bb027b260378ca393f0a0135830ed3b.jpg?size=200"
google_analytics: "UA-20365477-4"
disqus_account: 
github_repository: https://github.com/anonymoustafa
addthis_id: ra-513c6fa83da6ec67
post_limit: 11

# Social usernames/URLs
twitter_username: M_Ramezani
github_username:  anonymoustafa
instagram_username: mostafa.ramezani.90
reddit_username: 
linkedin_link: https://www.linkedin.com/in/mramezani/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: https://stackoverflow.com/users/5925160/darth-mostafa?tab=profile
xing_link: 
facebook_link: https://www.facebook.com/Mostafa.Ramezani.1990

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/M_Ramezani\">Mostafa Joon :)</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
